image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --update nodejs
  - npm install

stages:
  - test
  - build
  - deploy

test:
  script:
    - ./node_modules/mocha/bin/mocha

build:
  script:
    - docker -v
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN
    - docker build -t registry.gitlab.com/simoneromanelli/udemy-docker-ci-course:$CI_COMMIT_TAG .
