image: docker:latest

services:
  - docker:dind

before_script:
  - rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
  - yum install -y npm
  - npm install

stages:
  - test
  - build
  - deploy

test:
  script:
    - ./node_modules/mocha/bin/mocha

build:
  script:
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/simoneromanelli/udemy-docker-ci-course:$CI_COMMIT_TAG .
